sudo: false
dist: bionic

language: node_js

node_js:
  - 10
  - 12

cache: yarn

before_script:
  - yarn

script:
  - yarn test
  - yarn build

# after_success:
#   - id
#   - sudo apt update
#   - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
#   - pip3 install --user pipenv
#   - cd _util
#   - pipenv sync
#   - pipenv run python3 ./merge.py

notifications:
  slack:
    secure: "FoUmeprUVAUviLp6imQ2mRYuRjDZ94H/uXxEq1JVGnA42s3V6zFQuEQkwNF1kVWYtUyAg+3rHdN+m4WgskNlPrwpwtEjS0irxlomZ3deul6WdH0n6ME8dr3Gsh/kJRPQ3oPKkZ8noFQe1b2UacOQ6a1QrTIblM4GAhuBovjLVevrRw9gA0IFchgKJwz2oS8R7lNnPAORh19yiTy+Biab7XULIhTD95UxCHSlP+PFSIFm8NiCIX/1xXhDKIwEhWy3IsnfGuzpL8UOZrCdjnyNVNUAf03zYOmfBQqcMoeadf9+QrgDqKmItWzQZ3d7PrVK2Atrj4ijOCfHAw+s/fDK/8bD7zYwMGnHn1gQTa7CO7BKbKSqBLmnO8gV3e2CO7mtpQrgKhLsxE+iuy4lVm9JTVw3xnuetO4DUQIJiSEKDqLabzPfcYHAGpvHuj+CDC2UGYEPrrP5LUpKeSGz0TBb11LK8EwNVoDCe85Hd9zkkBAVkv4x1p4NFjSY/r3cd3HWqAXqCxZfzk/yttp/n67v9fMy5v6OXFQ3+p2CxR0uheRa8fPXthvSTHIkDCtDLmXIgZMoife2z2EqlusTdEDyuelkhzp9qtTVI3gxJNz1nSdAOGuYdeo5Q82QRT22Zs+NiEf8xDSn1ETo+GcLBp4fqqdnP0mfcEhqiwGheTPbujk="
